#.streamlit/secrets.toml
# .streamlit/secrets.toml
[mysql]

#host = "containers-us-west-188.railway.app"
#port = 7955
#database = "railway"
#user = "root"
#password = "1NCh6kaMZANctnYbPWFx"

host = "db4free.net"
port = 3306
database = "fahofaho"
user = "root_2023"
password = "C_AzFJD5csEEBRv"


#password = "C_AzFJD5csEEBRv"